# Author: Aleksandar Vladimirov Atanasov
# Description: YAML configuration file for the SR2 Dashboard when running on the SR2 mobile platform

dashboard:
  init:
    name: "SR2 Bringup"
    type: "noview"
    menu_entry:
      - app: "python"
        args: "/home/groten/rospy_rosparam_load_yaml.py"

  menus:
    - modules:
        - name: "Robotrainer Editor"
          type: "view"
          menu_entry: #rqt_graph, rqt_console
            buttons:
              - app: "python"
                args: "/home/groten/rospy_rosparam_load_yaml.py"
              - app: "kate"
                args: "/home/groten/force_yaml_test.yaml"
