# Author: Aleksandar Vladimirov Atanasov
# Description: YAML configuration file for the SR2 Dashboard used for testing new features or fixes

dashboard:
#  init: # Critical component representing an external process that is crucial
#        # for the proper working of the whole system. Until it is running the
#        # rest of the toolbar components are disabled
#        # In case it is terminated/crashes the rest of the toolbar components will be disabled
#        # (even if one or more of them (incl. views) run ext.processes that are independent from the critical process)
#    name: "Initialization"
#    type: "noview"
#    menu_entry:
#      #package: "cob_bringup"
#      #launch: "robot"
#      package: "lt"
#      launch: "talker"

  menus:
    - modules:
        - name: "Talker"
          type: "noview"
          menu_entry:
            icon: "~/catkin_ws/src/sr2_dashboard/resources/images/misc/ros.svg"
            package: "lt"
            node: "talker.py"
            #args: "some options" # Optional

        - name: "CoB Bringup"
          type: "view"
          menu_entry:
            icon: "~/catkin_ws/src/sr2_dashboard/resources/images/control/menu/view.svg"
            buttons:
              - service: "trigger_srv"
                timeout: 10
#                icon: "/home/atanasov2/catkin_ws/src/sr2_dashboard/resources/images/battery/battery-20.svg" # Absolute
#                icon: "resources/images/battery/battery-charge-100-green.svg" # Relative to given package for this entry
              - package: "lt"
                launch: "talker"
              - service: "trigger_srv"
                icon: "~/catkin_ws/src/sr2_dashboard/resources/images/misc/ros.svg"
              - service: "trigger_srv"
              - service: "trigger_srv"
              - package: "lt"
                launch: "listener"
              - service: "trigger_srv"
              - icon: "~/catkin_ws/src/sr2_dashboard/resources/images/misc/calculator.svg"
                app: "gnome-calculator"

    - modules:
        - name: "Listener"
          type: "noview"
          menu_entry:
            package: "lt"
            node: "listener.py"
            icon: "~/catkin_ws/src/sr2_dashboard/resources/images/status/status.svg"
        - name: "Testing"
          type: "view"
          menu_entry:
            icon: "~/catkin_ws/src/sr2_dashboard/resources/images/control/menu/view.svg"
            buttons:
              - name: "SR2 Mapping"
                package: "sr2_bringup"
                launch: "mapping"
              - package: "sr2_bringup"
                launch: "navigation"
              - package: "drive_program"
                launch: "combine.launch"
              - package: "drive_program"
                node: "drive_program"
              - name: "COB Bringup Initialization"
                package: "cob_bringup"
                launch: "robot"
        - name: "Call Trigger Service Server"
          type: "noview"
          menu_entry:
            service: "trigger_srv"
            timeout: 5 # In seconds | determines how long the application will wait for the specified service to be available
        - name: "Launch Trigger Service Server"
          type: "noview"
          menu_entry:
            icon: "~/catkin_ws/src/sr2_dashboard/resources/images/status/status.svg"
            package: "testing"
            node: "trigger_srv_server.py"

    - modules:
        # WARNING: some application behave differently based on whether a current instance of that same application is running or not (example: firefox, eclipse)
        - name: "RQT Graph"
          type: "noview"
          menu_entry: #rqt_graph, rqt_console
            app: "rqt_graph" # Arguments can be included inside the string; all arguments have to be separated by the command by a space
                             # Example: "firefox -new-tab www.google.com" will be split into: cmd="firefox" and args="-new-tab www.google.com
        - name: "Firefox Google"
          type: "noview"
          menu_entry:
            icon: "~/catkin_ws/src/sr2_dashboard/resources/images/misc/firefox.svg"
            app: "firefox"
            args: "-new-window www.google.com"
        - name: "Editor"
          type: "noview"
          menu_entry:
            icon: "~/catkin_ws/src/sr2_dashboard/resources/images/misc/gedit.svg"
            app: "gedit"
        - name: "Eclipse"
          type: "noview"
          menu_entry:
            icon: "~/catkin_ws/src/sr2_dashboard/resources/images/misc/eclipse.svg"
            app: "eclipse"
